"""Risk-controlled validation for proxy releases and generating mechanisms."""

from proxyguard.core import (
    MechanismAuditResult,
    ProxyAuditResult,
    RiskRequirement,
    SequentialAuditResult,
    audit_adaptive_candidate_stream,
    audit_proxy_candidates,
    audit_proxy_mechanisms,
    paired_prediction_losses,
)
from proxyguard.shared_target import (
    ConditionalSharedTargetPlan,
    ConditionalSharedTargetResult,
    SharedTargetPolynomialResult,
    SharedTargetReliabilityResult,
    SharedTargetTensorPolynomialResult,
    SharedTargetWitnessResult,
    bernstein_step_minorant,
    hybrid_reliability_lower_bound,
    plan_conditional_shared_target,
    shared_target_polynomial_lower_bound,
    shared_target_conditional_witness_lower_bound,
    shared_target_conditional_mean_lower_bound,
    shared_target_reliability_lower_bound,
    shared_target_tensor_polynomial_lower_bound,
    shared_target_witness_lower_bound,
    tensor_bernstein_design_minorant,
    tensor_bernstein_validity_minorant,
    witness_reliability_lower_from_mean,
)

__all__ = [
    "MechanismAuditResult",
    "ConditionalSharedTargetPlan",
    "ConditionalSharedTargetResult",
    "ProxyAuditResult",
    "RiskRequirement",
    "SequentialAuditResult",
    "SharedTargetPolynomialResult",
    "SharedTargetReliabilityResult",
    "SharedTargetTensorPolynomialResult",
    "SharedTargetWitnessResult",
    "audit_adaptive_candidate_stream",
    "audit_proxy_candidates",
    "audit_proxy_mechanisms",
    "bernstein_step_minorant",
    "paired_prediction_losses",
    "hybrid_reliability_lower_bound",
    "plan_conditional_shared_target",
    "shared_target_polynomial_lower_bound",
    "shared_target_conditional_witness_lower_bound",
    "shared_target_conditional_mean_lower_bound",
    "shared_target_reliability_lower_bound",
    "shared_target_tensor_polynomial_lower_bound",
    "shared_target_witness_lower_bound",
    "tensor_bernstein_design_minorant",
    "tensor_bernstein_validity_minorant",
    "witness_reliability_lower_from_mean",
]
